version: "3"
services:
  composer:
    build: ./docker/php/7.4
    entrypoint: composer
    volumes:
      - .:/home/alpine
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /home/alpine
